# -*- coding: utf-8 -*-
"""practicas unal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zq0Se1q9ZWIgS8lDMlawe7a5PjRgwhdY

# **PRACTICA 1.1**
"""

# Recibe la cadena de la entrada con la función 'input'.

cadena = input()

# 1) Convierte las minúsculas en mayúsculas.

mayus = cadena.upper()


# 2) Reemplaza la letra 'O' por 'OOO'.

cadena_o = mayus.replace ('O','OOO')


# 3) Añade los signos de exclamación "!!!!!" al final.

mensaje = f"{cadena_o} !!!!!"


# Envía el resultado a la salida con la función 'print'.

print (mensaje)

"""# **PRACTICA 1.2**"""

## 👇 Escriba su código DEBAJO de esta línea 👇 ##


# Reciba n y x de la entrada con la función 'input'.
# No olvide convertir las cadenas en números con 'int'.

n = input ()
x = input ()
num_x= int(x)
num_n = int(n)


# Calcula el número de grupos de tamaño x que se pueden formar.

grupos= num_n//num_x


# Calcula el número de estudiantes sobrantes asignados a la calificación.
# (Este número debe ser menor que x)

calificantes = num_n % num_x


# Calcula el número de reportes entregados por los estudiantes.

reportes = calificantes * grupos


# Imprime en la salida el número correspondiente para las preguntas del enunciado.


print (grupos)

print (reportes)

## ☝️ Escriba su código ENCIMA de esta línea ☝️ ##

"""# **TAREA 1.1**"""

##################################################
### 💻  Ejemplo: Ejercicios de física (I)  💻 ###
##################################################

## 👇 Escriba su código DEBAJO de esta línea 👇 ##


# 1) Obtener de la entrada del programa los parámetros iniciales.


x0 = input()
v0 = input()
a =  input()
t = input()


# 2) Convertir cada valor de texto obtenido de la entrada en un valor numérico decimal.
x01 = float(x0)
v01 = float(v0)
a0 = float(a)
t0 = float(t)


# 3) Utilizar los valores numéricos en una expresión matemática y obtener el valor de la posición final.


x = x01+v01*t0+((1/2)*a0*(t0**2))


# 4) Reportar el resultado de la operación con dos dígitos decimales.

print (f"La posición final es {x:.2f} metros")



## ☝️ Escriba su código ENCIMA de esta línea ☝️ ##



"""# **TAREA 1.2**"""

##################################################
#### 💻 Tarea: Ejercicios de física (II)  💻 ####
##################################################

## 👇 Escriba su código DEBAJO de esta línea 👇 ##


# 1) Obtener de la entrada del programa los parámetros iniciales.


x0 = input()
v0 = input()
a =  input()
t = input()


# 2) Convertir cada valor de texto obtenido de la entrada en un valor numérico decimal.

x01 = float(x0) ##entrada en m
v01 = float(v0) ##entrada en km/h
a0 = float(a)  ##entrada en m/s^2
t0 = float(t) ## entrada en s



# 3) Realizar las operaciones matemáticas para las conversiones de unidad de medida necesarias.
xkm = x01/1000 ## m a km
vms = v01/3.6 ## km/h a m/s




# 4) Utilizar los valores numéricos en las expresiones matemáticas de cada ecuación y obtener el valor de:


#     i. Posición final

x = x01 + vms*t0+0.5*a0*(t0**2)


#     ii. Velocidad final.

v = vms + a0*t0 #salida en metros por segundo
vkmh = v*3.6 ## m/s a km/h

# 5) Reportar el resultado de la operación con el formato solicitado.

print (f"La posición final es de {x:.2f} m y la velocidad es de {vkmh:.6f} km/h")




## ☝️ Escriba su código ENCIMA de esta línea ☝️ ##

"""# **PRACTICA 2.1**"""

### ESCRIBA SU CÓDIGO A PARTIR DE AQUÍ ### (~ 7-10 líneas de código)
# Entrada del programa (~ 6 líneas).
# Posición y dimensiones del rectángulo.
x = float(input())
y = float(input())
w = float(input())
h = float(input())

# Posición del punto.
px = float(input())
py = float(input())

# Operación booleana y salida del programa (~ 1-4 líneas).
Resultado = (x<=px<=x+w) and (y<=py<=y+h)
print(Resultado)